### ISSUE TITLE
Add to description of extension that you have to explicitly bind it (as the default doesn't work)

### ISSUE THREAD

**Issue by Psykar** [EtaoinWu/smart-ctrl-w#3]
I went and made my own before I discovered this.

https://chrome.google.com/webstore/detail/cjphhjhompmhhjkdaalfgbegnbimonoj

Pretty much identical to yours except for the navigate to last non pinned tab part.

**Comment by EtaoinWu** [comment]
Thank you for pointing this out. I have changed the github readme in a716e15, but the change on Chrome webstore "overview" part is pending review.
